FRI-123 Update classification PAC/SAC automatically
IHTSDO/snowstorm pull request #296
Opened 2021-07-15 16:17 UTC by dmcgihtsdo

FRI-123 is concerned with updating the PAC/SAC classification criteria on AAG whenever a commit is made. 

The majority of the functionality was written in FRI-61; this PR simply adds support for an edge case where the classification results are empty (as this does not trigger a commit).

2021-07-15 16:17 UTC, dmcgihtsdo commented on src/main/java/org/snomed/snowstorm/core/data/services/BranchMetadataHelper.java
> +	public static final String CLASSIFIED_KEY = "classified";
I couldn't find a constant for classified, so I added it here beside what I also had to use.

2021-07-15 16:18 UTC, dmcgihtsdo commented on src/main/java/org/snomed/snowstorm/core/data/services/classification/ClassificationService.java
> +												mockCommitCompletion(latestBranchCommit);
This method is triggered whenever a classification is completed.

2021-07-15 16:18 UTC, dmcgihtsdo commented on src/main/java/org/snomed/snowstorm/core/data/services/classification/ClassificationService.java
> +			mockCommitCompletion(path, classification);
This method is triggered whenever a classification is updated manually.

2021-07-23 15:03 UTC, kaicode requested changes
The branch classification status is already being set via `BranchClassificationStatusService.setClassificationStatus`. 
The only case I can think of where a classification status change is not already being sent to the AAG is when classification completes and there are no changes - in this situation the metadata is being updated but we need to post to the AAG. We already do this when creating a branch.

2021-08-06 12:52 UTC, dmcgihtsdo commented
> The branch classification status is already being set via `BranchClassificationStatusService.setClassificationStatus`.
> The only case I can think of where a classification status change is not already being sent to the AAG is when classification completes and there are no changes - in this situation the metadata is being updated but we need to post to the AAG. We already do this when creating a branch.

Sorry @kaicode , I don't quite understand. 

I think I'm already doing what you've said? For my testing, I've created a new branch, and then started a classification. The classification finishes with no Relationship changes and ends up at line 248 in ClassificationService. I am then sending a request to AAG with this information.

2021-08-09 09:25 UTC, kaicode commented
@dmcgihtsdo I am not suggesting what you have done will not work, I'm just suggesting that we could have more code reuse if you look at the other places where we are doing the same thing. I'll call you.

2021-08-09 10:25 UTC, dmcgihtsdo commented
> @dmcgihtsdo I am not suggesting what you have done will not work, I'm just suggesting that we could have more code reuse if you look at the other places where we are doing the same thing. I'll call you.

Thanks for the clarification Kai. 

I have removed the unnecessary call to the mock method (which also contained the redundant constant). Now all that is changed is the call to AAG when an empty classification.

2021-08-09 12:13 UTC, kaicode approved these changes
Looks good to me 👍

2021-08-09 14:01 UTC, merged